### ISSUE TITLE
how to control the width of drop-down list

### ISSUE THREAD

**Issue by bulabula001** [snapappointments/bootstrap-select#1793]
hi all,
i have be in trouble with that when the text of in the option is long enough,  the  drop-down list either become more and more wide, 
so how can i control the width of the drop-down list,.

Thanks & Bestregards.
bulabula

**Comment by sansjunk** [comment]
@bulabula001 Try using the `data-content` attribute on the `option` element. See [here](http://jsfiddle.net/t0xicCode/454Lqbz8/)

**Comment by iyadthayyil** [comment]
fixed #1034

**Comment by bulabula001** [comment]
tks @iyadthayyil

**Comment by leonp5** [comment]
I still have the issue with v. 1.13.12 (package.json) (in the bootstrap-select.css it says, that is v. 1.13.18).

When i select a certain count of options the select box begin to grow and with every additional it grows more. Looks like this:

![grafik](https://user-images.githubusercontent.com/56833783/97307537-1f8a0c80-1860-11eb-8510-87ae8470464f.png)

Thats the HTLM Structure (in a Twig template):

```


<div class="col-xl-6">
                            <div class="form-group">
                                <label>{{ "job.wizard.two.region" | trans }}</label>
                                <select
                                    class="form-control form-control-solid form-control-lg selectpicker"
                                    name="job_ad_visible_region[]"
                                    data-size="9"
                                    {# data-width="300px" #}
                                    multiple>
                                    {% for region in regions %}
                                        <option
                                            value="{{ region.getRegionId() }}"
                                            selected="selected">{{ region.getNameDe() }}</option>
                                    {% endfor %}
                                </select>
                                <span class="form-text text-muted">{{ "job.wizard.two.region.subtitle" | trans }}</span>
                            </div>

                        </div>

```
The only way to handle it is the `data-width` attribute. But with this, the select field isn't really responsive.

I'm not sure, if it is really fixed, because here #1853 is said, that the fix is lost.
