### ISSUE TITLE
Live Search Data-tokens Regardless of Order

### ISSUE THREAD

**Issue by catecomm** [snapappointments/bootstrap-select#1905]
I have the following option with these data tokens..

`data-tokens="US Congress New York House Senate"`

When I do the live search, it'll only show this option if the keywords are typed in that exact order. If I type "House Congress" it won't work, and if I do "US Senate" it won't work.

I have `data-live-search-style="contains"` set thinking contains would have solved this, but it doesn't. Is there a way to get the live search to not care about token order?

**Comment by caseyjhol** [comment]
This was addressed in v1.13.0-beta. I've moved development of this plugin to a new repo, and v1.13.0-beta can be downloaded here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta.

**Comment by catecomm** [comment]
I started using 1.13.0-beta and it still doesn't fix the issue I had. I tried typing "US Senate" based off of data-tokens="US Congress New York House Senate" and once I start typing Senate no results show up.

**Comment by caseyjhol** [comment]
Okay - I'll look into this further.

**Comment by NicolasCARPi** [comment]
@catecomm please try latest version.
