### ISSUE TITLE
Using / for division is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by idubinets** [snapappointments/bootstrap-select#2677]
Hi guys,

can you please fix the warning:

![image](https://user-images.githubusercontent.com/2304959/143229984-56c2633d-faf1-43f1-9836-dec201a78d30.png)

**Comment by NicolasCARPi** [comment]
This is fixed in latest version.

**Comment by johnny-solargard** [comment]
@NicolasCARPi - in which version was this fixed?  I'm still seeing the error when using 1.13.18 and the 1.14-betas 

Thanks!

**Comment by NicolasCARPi** [comment]
It is fixed in `dev` branch. Hopefully a new beta will be released soonish.
